name: cff
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2.2
  - scipy1.15.1
  - pandas=2.2.3
  - openpyxl=3.1.5
  - country_converter=1.2
  - geopandas=1.0.1
  - matplotlib=3.10
  - seaborn=0.13.2
  - networkx=3.4.2
  - tqdm=4.67.1
  - pytest=8.3.4
  - pip=25.0.1
  - pip:
    - cpi=2.0.5

