name: cff
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - openpyxl
  - country_converter
  - geopandas
  - matplotlib
  - seaborn
  - networkx
  - tqdm
  - pytest
  - pip
  - pip:
    - cpi

